server:
  port: 8080
  address: 0.0.0.0

spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: /nutri-ai
  ai:
    chat:
      client:
        enabled: false
    dashscope:
      chat:
        api-key: ${AI_DASHSCOPE_API_KEY}
      embedding:
        api-key: ${AI_DASHSCOPE_API_KEY}
  jpa:
    database: h2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

app:
  env: DEV
  models:
    providers:
      dashscope:
        vision: qwen3-vl-plus
        text: qwen-flash
        chat: qwen-flash
        embed: qwen3-rerank
  jwt:
    secret: 0iAKwlb7ZP4OG5qlRYCIGdrfKwNRJ6K5QhRZJqVhxf8=
    excludePaths:
      - /web/user/signUp
      - /web/user/signIn
      - /web/user/callback/**
  cors:
    allowed-origins:
      - "*"
    allowed-methods:
      - "GET"
      - "POST"
    allowed-headers:
      - "*"
    allow-credentials: false
    max-age: 3600