server:
  port: 8080
  servlet:
    context-path: /nutri-ai

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  ai:
    chat:
      client:
        enabled: false
    dashscope:
      chat:
        api-key: ${AI_DASHSCOPE_API_KEY}


model-list:
  vision: qwen-vl-plus
  text: qwen-flash